# .github/workflows/job-scraper.yml
name: Automated Job Scraper

on:
  schedule:
    # Run 4 times a day: 6 AM, 12 PM, 6 PM, 12 AM UTC
    - cron: '0 6 * * *'   # 6 AM UTC
    - cron: '0 12 * * *'  # 12 PM UTC
    - cron: '0 18 * * *'  # 6 PM UTC
    - cron: '0 0 * * *'   # 12 AM UTC

  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job scraper
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python github_actions_job_scraper.py

    - name: Commit and push job data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add job_data/
        git diff --staged --quiet || git commit -m "Update job data - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}